package codigos;

import java.io.*;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cliente
 */
public class cadastrarEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form cadastrarEmprestimo
     */
    public static String veri2 = "0";
    public cadastrarEmprestimo() {
        initComponents();
        Color fundo = new Color(253,236,166);
        getContentPane().setBackground(fundo);
        try {
            Arquivo2();
        } catch (IOException ex) {
            
        }
    }
    public void Arquivo2() throws IOException {
        BufferedReader fr = new BufferedReader(new FileReader("pesquisa_resultadoE.txt"));
        
        try {
            String linha,titulo2 = null,anodolivro2 = null,editora2 = null,autor2 = null,genero2 = null;
            
            while(fr.ready()){
                linha = fr.readLine();
                String[] campos = linha.split(";");
                titulo2 = campos[0];
                anodolivro2 = campos[1];
                editora2 = campos[2];
                autor2 = campos[3];
                genero2 = campos[4];
                veri2 = campos[6];
                
            }
            if(veri2.equals("2")){
                titulo.setText(titulo2);
                anodolivro.setText(anodolivro2); 
                editora.setText(editora2);
                autor.setText(autor2);
                genero.setText(genero2);
                BufferedWriter fw;          
                try {
                    fw = new BufferedWriter(new FileWriter("pesquisa_resultadoE.txt"));

                    fw.close();

                } catch (IOException ex) {
                    Logger.getLogger(pesquisarLivro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                
            
            fr.close();
        
        }catch (IOException e){
            System.out.println("Erro na leitura do arquivo.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        autor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        genero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        anodolivro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nomeLeitor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        ano = new javax.swing.JTextField();
        salvar1 = new javax.swing.JButton();
        editora = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("blioteca Chá da Tarde");
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 50)); // NOI18N
        jLabel4.setText("Emprestrar");

        jPanel1.setBackground(new java.awt.Color(253, 236, 166));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        pesquisar.setBackground(new java.awt.Color(255, 255, 153));
        pesquisar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa.png"))); // NOI18N
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel3.setText("Titulo:");

        titulo.setBackground(new java.awt.Color(51, 51, 51));
        titulo.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel5.setText("Genero:");

        autor.setBackground(new java.awt.Color(51, 51, 51));
        autor.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        autor.setForeground(new java.awt.Color(255, 255, 255));
        autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel6.setText("Autor:");

        genero.setBackground(new java.awt.Color(51, 51, 51));
        genero.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        genero.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel7.setText("Ano:");

        anodolivro.setBackground(new java.awt.Color(51, 51, 51));
        anodolivro.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        anodolivro.setForeground(new java.awt.Color(255, 255, 255));
        anodolivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anodolivroActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel8.setText("Informacão do livro");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel9.setText("dados do leitor ");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel10.setText("Telefone:");

        nomeLeitor.setBackground(new java.awt.Color(51, 51, 51));
        nomeLeitor.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        nomeLeitor.setForeground(new java.awt.Color(255, 255, 255));
        nomeLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeLeitorActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel11.setText("Nome:");

        telefone.setBackground(new java.awt.Color(51, 51, 51));
        telefone.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        telefone.setForeground(new java.awt.Color(255, 255, 255));
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel12.setText("Data de devolução:");

        dia.setBackground(new java.awt.Color(51, 51, 51));
        dia.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        dia.setForeground(new java.awt.Color(255, 255, 255));
        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });

        mes.setBackground(new java.awt.Color(51, 51, 51));
        mes.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        mes.setForeground(new java.awt.Color(255, 255, 255));
        mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesActionPerformed(evt);
            }
        });

        ano.setBackground(new java.awt.Color(51, 51, 51));
        ano.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        ano.setForeground(new java.awt.Color(255, 255, 255));
        ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoActionPerformed(evt);
            }
        });

        salvar1.setBackground(new java.awt.Color(255, 255, 153));
        salvar1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        salvar1.setText("salvar");
        salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar1ActionPerformed(evt);
            }
        });

        editora.setBackground(new java.awt.Color(51, 51, 51));
        editora.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        editora.setForeground(new java.awt.Color(255, 255, 255));
        editora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editoraActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel15.setText("Editora:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(titulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(autor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editora))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefone))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(anodolivro, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 459, Short.MAX_VALUE)
                        .addComponent(salvar1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(anodolivro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        voltar.setBackground(new java.awt.Color(255, 255, 153));
        voltar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        jLabel1.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel2.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel13.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel14.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(789, 789, 789)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(69, 69, 69))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(voltar)
                                .addGap(45, 45, 45)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(voltar)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        setSize(new java.awt.Dimension(768, 468));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        pesquisarLivro frame = new pesquisarLivro();
        frame.setVisible(rootPaneCheckingEnabled);
        cadastrarEmprestimo.this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarActionPerformed

    private void tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloActionPerformed

    private void autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorActionPerformed

    private void anodolivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anodolivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anodolivroActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
            emprestimo frame = new emprestimo();
            frame.setVisible(rootPaneCheckingEnabled);
            cadastrarEmprestimo.this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarActionPerformed

    private void nomeLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeLeitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeLeitorActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaActionPerformed

    private void mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesActionPerformed

    private void anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoActionPerformed

    private void salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar1ActionPerformed

        String titulo1, autor1, genero1, nome1,anodolivro1, telefone1, dia1, mes1, ano1,editora1;
        int verifica[] = new int[2];
        String numeros[] = new String[1];
        
        titulo1 = titulo.getText().toLowerCase();
        editora1 = editora.getText().toLowerCase();
        autor1 = autor.getText().toLowerCase();
        genero1 = genero.getText().toLowerCase();
        anodolivro1 = anodolivro.getText().toLowerCase();

        nome1 = nomeLeitor.getText().toLowerCase();
        telefone1 = telefone.getText().toLowerCase();
        dia1 = dia.getText().toLowerCase();
        mes1 = mes.getText().toLowerCase();
        ano1 = ano.getText().toLowerCase();

        if(titulo1.equals("") || editora1.equals("") || autor1.equals("") || genero1.equals("") || anodolivro1.equals("") || nome1.equals("") || telefone1.equals("") || dia1.equals("") || mes1.equals("") || ano1.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Todos os campos são obrigatorios", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                BufferedWriter fw = new BufferedWriter(new FileWriter("Emprestimos.txt",true));          
                PrintWriter pw = new PrintWriter (fw);
                Verificar(titulo1, autor1,genero1,anodolivro1,editora1,verifica);
                protocolo(numeros);
                if(verifica[0]== 1){
                    if(verifica[1]==1){
                        pw.println(titulo1+";"+anodolivro1+";"+editora1+";"+autor1+";"+genero1+";"+nome1+";"+telefone1+";"+dia1+";"+mes1+";"+ano1+";"+numeros[0]);
                        JOptionPane.showMessageDialog(rootPane, "Sucesso\nSeu protocolo é:" + numeros[0], "Lembrete",JOptionPane.INFORMATION_MESSAGE);
                        editar(titulo1,anodolivro1,editora1,autor1,genero1);
                        titulo.setText("");
                        autor.setText("");
                        genero.setText("");
                        anodolivro.setText("");
                        nomeLeitor.setText("");
                        telefone.setText("");
                        dia.setText("");
                        mes.setText("");
                        ano.setText("");
                        editora.setText("");
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "livro indisponivel", "Aviso", JOptionPane.WARNING_MESSAGE);
                    }
                } else{
                    JOptionPane.showMessageDialog(rootPane, "livro não existente", "Aviso", JOptionPane.WARNING_MESSAGE);

                }

                pw.close();
            } catch (HeadlessException | IOException e) {
                JOptionPane.showMessageDialog(rootPane, "Erro na gravação do arquivo." + e);
            }
        }
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_salvar1ActionPerformed

    private void editoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editoraActionPerformed
    public static int[] Verificar(String titulo1, String autor1, String genero1, String anodolivro1, String editora1, int verifica[]) throws FileNotFoundException{
        BufferedReader fr = new BufferedReader(new FileReader("Acervo.txt"));
        String titulo2, autor2, genero2, anodolivro2, editora2;
        int status;
        verifica[0] = 0;
        try{
            String linhalida;
            int q= 0;
            
            while(fr.ready() && verifica[0]==0){
                linhalida = fr.readLine();
                String[] campos = linhalida.split(";");
                titulo2 = campos[0];
                anodolivro2 = campos[1];
                editora2 = campos[2];
                autor2 = campos[3];
                genero2 = campos[4];
                status = Integer.parseInt(campos[5]);
                
                if(titulo2.equals(titulo1) && autor2.equals(autor1) && genero2.equals(genero1) && anodolivro2.equals(anodolivro1) && editora2.equals(editora1)){
                    verifica[0] = 1;
                    if(status ==1 ){verifica[1] = status;}
                    
                }
                
            }
            
            fr.close();
        } catch (IOException e){
            
        }
        
        return verifica;
    }
    public static void editar(String titulo1, String anodolivro1, String editora1, String autor1, String genero1) throws FileNotFoundException, IOException{
        BufferedReader fr = new BufferedReader(new FileReader("Acervo.txt"));

        String titulo2[] = new String[1000];
        String autor2[] = new String[1000];
        String genero2[] = new String[1000];
        String anodolivro2[] = new String[1000];
        String editora2[] = new String[1000];  
        int status2[] = new int[1000];
        try{
            String linhalida;
            int q= 0;
     
            while(fr.ready()){
                linhalida = fr.readLine();
                String[] campos = linhalida.split(";");
                titulo2[q] = campos[0];
                anodolivro2[q] = campos[1];
                editora2[q] = campos[2];
                autor2[q] = campos[3];
                genero2[q] = campos[4];
                status2[q] = Integer.parseInt(campos[5]);
                if(titulo1.equals(titulo2[q]) && autor1.equals(autor2[q]) && genero1.equals(genero2[q]) && anodolivro1.equals(anodolivro2[q]) && editora1.equals(editora2[q])){
                      status2[q] = 0;
                }
                
                q++;
            }
            
            BufferedWriter fw = new BufferedWriter(new FileWriter("Acervo.txt"));          
            PrintWriter pw = new PrintWriter (fw);
            
            for(int i = 0;i<q;i++){
                pw.println(titulo2[i]+";"+anodolivro2[i]+";"+editora2[i]+";"+autor2[i]+";"+genero2[i]+";"+status2[i]);
            }
            fw.close();
            fr.close();
        } catch (IOException e){
            
        }
    }
    public static String[] protocolo(String numeros[]) throws FileNotFoundException{ 
        Random registro = new Random(); 
        String n1, n2, n3, n4, n5, n6; 
         
        BufferedReader fr = new BufferedReader(new FileReader("Emprestimos.txt")); 
        String protocolo[] = new String[200]; 

        try{ 
            String linhalida; 
            int q= 0, verificador=1; 


            while(verificador == 1){ 
                verificador = 0; 
                n1 = Integer.toString(registro.nextInt(9)); 
                n2 = Integer.toString(registro.nextInt(9)); 
                n3 = Integer.toString(registro.nextInt(9)); 
                n4 = Integer.toString(registro.nextInt(9)); 
                n5 = Integer.toString(registro.nextInt(9)); 
                n6 = Integer.toString(registro.nextInt(9)); 

                numeros[0] = n1 + n2 + n3 + n4 + n5 + n6; 

                while(fr.ready()){ 
                    linhalida = fr.readLine(); 
                    String[] campos = linhalida.split(";"); 
                    protocolo[q] = campos[9]; 

                    if(protocolo[q].equals(numeros[0])){ 
                        verificador = 1; 
                    } 
                } 
            } 
            fr.close(); 
        } catch (IOException e){ } 
        return numeros; 
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastrarEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ano;
    private javax.swing.JTextField anodolivro;
    private javax.swing.JTextField autor;
    private javax.swing.JTextField dia;
    private javax.swing.JTextField editora;
    private javax.swing.JTextField genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mes;
    private javax.swing.JTextField nomeLeitor;
    private javax.swing.JButton pesquisar;
    private javax.swing.JButton salvar1;
    private javax.swing.JTextField telefone;
    private javax.swing.JTextField titulo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
