package codigos;

import java.io.*;
import java.awt.Color;
import java.io.IOException;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cliente
 */
public class devolver extends javax.swing.JFrame {

    /**
     * Creates new form cadastrarEmprestimo
     */
    public devolver() {
        initComponents();
        Color fundo = new Color(253,236,166);
        getContentPane().setBackground(fundo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        salvar1 = new javax.swing.JButton();
        protocolo = new javax.swing.JTextField();
        voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("blioteca Chá da Tarde");
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 50)); // NOI18N
        jLabel4.setText("Emprestrar");

        jPanel1.setBackground(new java.awt.Color(253, 236, 166));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel9.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel9.setText("Digite o numero do protocolo:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        salvar1.setBackground(new java.awt.Color(255, 255, 153));
        salvar1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        salvar1.setText("Confirmar");
        salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar1ActionPerformed(evt);
            }
        });

        protocolo.setBackground(new java.awt.Color(51, 51, 51));
        protocolo.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        protocolo.setForeground(new java.awt.Color(255, 255, 255));
        protocolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protocoloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(salvar1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(protocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(protocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salvar1)
                .addGap(59, 59, 59))
        );

        voltar.setBackground(new java.awt.Color(255, 255, 153));
        voltar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        jLabel1.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel2.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel13.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel14.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(voltar)
                                .addGap(61, 61, 61)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(766, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        emprestimo frame = new emprestimo();
        frame.setVisible(rootPaneCheckingEnabled);
        devolver.this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarActionPerformed

    private void salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar1ActionPerformed
        int a;
        String protocolo1 = protocolo.getText();
        try {
            a = Manipulacao2(protocolo1);
            if(a==1){
                JOptionPane.showMessageDialog(rootPane, "Livro delvovido", "Lembrete",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "emprestimo não existente", "Lembrete",JOptionPane.INFORMATION_MESSAGE);
            }
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(devolver.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_salvar1ActionPerformed
    public static int Manipulacao2 (String registro) throws FileNotFoundException, IOException{
        BufferedReader fr = new BufferedReader(new FileReader("Emprestimos.txt"));
        String Registro1[] = new String[1000];
        String titulo2, autor2, genero2, anodolivro2, editora2;

        int verificador = 0;

        try{
            String linhalida;
            int q= 0;

            while(fr.ready() && verificador==0){
                linhalida = fr.readLine();
                String[] campos = linhalida.split(";");
                Registro1[q] = campos[10];

                if(registro.equals(Registro1[q])){
                    verificador = 1;
                    titulo2 = campos[0];
                    anodolivro2 = campos[1];
                    editora2 = campos[2];
                    autor2 = campos[3];
                    genero2 = campos[4];
                    editar3(titulo2, autor2, genero2, anodolivro2, editora2);
                    Apagardevolucao4(titulo2, autor2, genero2, anodolivro2, editora2);
                 }
            }
            fr.close(); 
        }
        catch(IOException e){}
        return verificador;
    }
    public static void editar3(String titulo2, String autor2, String genero2, String anodolivro2, String editora2) throws FileNotFoundException, IOException{
        BufferedReader fr = new BufferedReader(new FileReader("Acervo.txt"));

        String titulo3[] = new String[200];
        String autor3[] = new String[200];
        String genero3[] = new String[200];
        String anodolivro3[] = new String[200]; 
        String editora3[] = new String[200];
        int status3[] = new int[200];
        try{
            String linhalida;
            int q= 0;

            while(fr.ready()){
            linhalida = fr.readLine();
            String[] campos = linhalida.split(";");
            titulo3[q] = campos[0];
            anodolivro3[q] = campos[1];
            editora3[q] = campos[2];
            autor3[q] = campos[3];
            genero3[q] = campos[4];
            status3[q] = Integer.parseInt(campos[5]);

            if(titulo2.equals(titulo3[q]) && autor2.equals(autor3[q]) && genero2.equals(genero3[q]) && anodolivro2.equals(anodolivro3[q]) && editora2.equals(editora3[q])){
                status3[q] = 1;
            }
            q++;
            }

            BufferedWriter fw = new BufferedWriter(new FileWriter("Acervo.txt"));          
            PrintWriter pw = new PrintWriter (fw);

            for(int i = 0;i<q;i++){
                pw.println(titulo3[i]+";"+anodolivro3[i]+";"+editora3[i]+";"+autor3[i]+";"+genero3[i]+";"+status3[i]);
            }
            fw.close();
            fr.close();
        } catch (IOException e){}
    }
    public static void Apagardevolucao4(String titulo2, String autor2, String genero2, String anodolivro2, String editora2) throws FileNotFoundException, IOException{
        BufferedReader fr = new BufferedReader(new FileReader("Emprestimos.txt"));

        String titulo4[] = new String[200];
        String autor4[] = new String[200];
        String genero4[] = new String[200];
        String anodolivro4[] = new String[200];     
        String nome4[] = new String[200];
        String telefone4[] = new String[200];
        String dia4[] = new String[200];
        String mes4[] = new String[200];
        String ano4[] = new String[200];
        String protocolo4[] = new String[200];
        String editora4[] = new String[200];

        try{
            String linhalida;
            int q= 0;

            while(fr.ready()){
                linhalida = fr.readLine();
                String[] campos = linhalida.split(";");
                titulo4[q] = campos[0];
                anodolivro4[q] = campos[1];
                editora4[q] = campos[2];
                autor4[q] = campos[3];
                genero4[q] = campos[4];
                
                nome4[q] = campos[5]; 
                telefone4[q] = campos[6]; 
                dia4[q] = campos[7]; 
                mes4[q] = campos[8]; 
                ano4[q] = campos[9]; 
                protocolo4[q] = campos[10];
                q++;
             }

            BufferedWriter fw = new BufferedWriter(new FileWriter("Emprestimos.txt"));          
            PrintWriter pw = new PrintWriter (fw);

            for(int i = 0;i<q;i++){
                if(titulo2.equals(titulo4[i]) && autor2.equals(autor4[i]) && genero2.equals(genero4[i]) && anodolivro2.equals(anodolivro4[i]) && editora2.equals(editora4[i])){
                }
                else{
                    pw.println(titulo4[i]+";"+anodolivro4[i]+";"+editora4[i]+";"+autor4[i]+";"+genero4[i]+";"+nome4[i]+";"+telefone4[i]+";"+dia4[i]+";"+mes4[i]+";"+ano4[i]+";"+protocolo4[i]);
                }
            }
            fw.close();
            fr.close();
        } catch (IOException e){}
    }
    private void protocoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protocoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_protocoloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastrarEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField protocolo;
    private javax.swing.JButton salvar1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
