package codigos;


import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cliente
 */
public class pesquisarLivro extends javax.swing.JFrame {

    /**
     * Creates new form pesquisarLivro
     */
    public pesquisarLivro() {
        initComponents();
        Color fundo = new Color(253,236,166);
        getContentPane().setBackground(fundo);
        try {
            // TODO add your handling code here:
            Arquivo2();
        } catch (IOException ex) {
            
        }
    }
    public void Arquivo2() throws IOException {
        BufferedReader fr = new BufferedReader(new FileReader("Acervo.txt"));
        String titulo2[] = new String[1000];
        String autor2[] = new String[1000];
        String genero2[] = new String[1000];
        String anodolivro2[] = new String[1000];
        String editora2[] = new String[1000];  
        int status2[] = new int[1000]; 
        
        try {
            int q= 0;
            String linha;
            
            while(fr.ready()){
                linha = fr.readLine();
                String[] campos = linha.split(";");
                titulo2[q] = campos[0];
                anodolivro2[q] = campos[1];
                editora2[q] = campos[2];
                autor2[q] = campos[3];
                genero2[q] = campos[4];
                status2[q] = Integer.parseInt(campos[5]);
                
                if(status2[q] == 1){
                    DefaultTableModel teste = (DefaultTableModel) livros.getModel();
                    Object[] dados = {titulo2[q],anodolivro2[q],editora2[q],autor2[q],genero2[q],"Disponivel"};
                    teste.addRow(dados);
                } else{
                    DefaultTableModel teste = (DefaultTableModel) livros.getModel();
                    Object[] dados = {titulo2[q],anodolivro2[q],editora2[q],autor2[q],genero2[q],"Indisponivel"};
                    teste.addRow(dados);
                }
                q++;
            }
            
            
            fr.close();
        
        }catch (IOException e){
            System.out.println("Erro na leitura do arquivo.");
        }
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pesquisarAcao = new javax.swing.JButton();
        pesquisa = new javax.swing.JComboBox<>();
        pesquisaConteudo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        livros = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Chá da Tarde");
        setResizable(false);

        jLabel1.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel4.setFont(new java.awt.Font("Impact", 0, 50)); // NOI18N
        jLabel4.setText("Acervo");

        jPanel1.setBackground(new java.awt.Color(253, 236, 166));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        pesquisarAcao.setBackground(new java.awt.Color(255, 255, 153));
        pesquisarAcao.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        pesquisarAcao.setText("Pesquisar");
        pesquisarAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarAcaoActionPerformed(evt);
            }
        });

        pesquisa.setBackground(new java.awt.Color(255, 255, 153));
        pesquisa.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        pesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titulo", "Ano", "Editora", "Autor", "Genero" }));
        pesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pesquisaConteudo.setBackground(new java.awt.Color(51, 51, 51));
        pesquisaConteudo.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        pesquisaConteudo.setForeground(new java.awt.Color(255, 255, 255));
        pesquisaConteudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaConteudoActionPerformed(evt);
            }
        });

        livros.setBackground(new java.awt.Color(255, 255, 153));
        livros.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        livros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Ano", "Editora", "Autor", "Genero", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        livros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                livrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(livros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisaConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisarAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisaConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarAcao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        voltar.setBackground(new java.awt.Color(255, 255, 153));
        voltar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(voltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel2)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(766, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarAcaoActionPerformed
        String opcao, conteudo;
        opcao = String.valueOf(pesquisa.getSelectedItem());
        conteudo = pesquisaConteudo.getText();
        
        if(conteudo.equals("")){
            JOptionPane.showMessageDialog(rootPane, "pesquisa vazia", "Aviso", JOptionPane.WARNING_MESSAGE);
        }else{
            String titulo2[] = new String[1000];
            String autor2[] = new String[1000];
            String genero2[] = new String[1000];
            String anodolivro2[] = new String[1000];
            String editora2[] = new String[1000];  
            int status2[] = new int[1000];
            String titulor[] = new String[1000];
            String autorr[] = new String[1000];
            String generor[] = new String[1000];
            String anodolivror[] = new String[1000];
            String editorar[] = new String[1000];  
            int statusr[] = new int[1000];

            try{
                BufferedReader fr = new BufferedReader(new FileReader("Acervo.txt"));
                String linhalida;
                int q= 0;

                while(fr.ready()){
                    linhalida = fr.readLine();
                    String[] campos = linhalida.split(";");
                    titulo2[q] = campos[0];
                    anodolivro2[q] = campos[1];
                    editora2[q] = campos[2];
                    autor2[q] = campos[3];
                    genero2[q] = campos[4];
                    status2[q] = Integer.parseInt(campos[5]);
                    q++;
                }
                int tam = 0;
                switch(opcao){
                    case "Titulo":
                        for(int i = 0; i<q;i++){
                            if(conteudo.equals(titulo2[i])){
                                titulor[tam] = titulo2[i];
                                anodolivror[tam] = anodolivro2[i];
                                editorar[tam] = editora2[i];
                                autorr[tam] = autor2[i];
                                generor[tam] = genero2[i];
                                statusr[tam] = status2[i];
                                tam++;
                            }
                        }
                        break;
                    case "Ano":
                        for(int i = 0; i<q;i++){
                            if(conteudo.equals(anodolivro2[i])){
                                titulor[tam] = titulo2[i];
                                anodolivror[tam] = anodolivro2[i];
                                editorar[tam] = editora2[i];
                                autorr[tam] = autor2[i];
                                generor[tam] = genero2[i];
                                statusr[tam] = status2[i];
                                tam++;
                            }
                        }
                        break;
                    case "Genero":
                        for(int i = 0; i<q;i++){
                            if(conteudo.equals(genero2[i])){
                                titulor[tam] = titulo2[i];
                                anodolivror[tam] = anodolivro2[i];
                                editorar[tam] = editora2[i];
                                autorr[tam] = autor2[i];
                                generor[tam] = genero2[i];
                                statusr[tam] = status2[i];
                                tam++;
                            }
                        }
                        break;
                    case "Autor":
                        for(int i = 0; i<q;i++){
                            if(conteudo.equals(autor2[i])){
                                titulor[tam] = titulo2[i];
                                anodolivror[tam] = anodolivro2[i];
                                editorar[tam] = editora2[i];
                                autorr[tam] = autor2[i];
                                generor[tam] = genero2[i];
                                statusr[tam] = status2[i];
                                tam++;
                            }
                        }
                        break;
                    case "Editora":
                        for(int i = 0; i<q;i++){
                            if(conteudo.equals(editora2[i])){
                                titulor[tam] = titulo2[i];
                                anodolivror[tam] = anodolivro2[i];
                                editorar[tam] = editora2[i];
                                autorr[tam] = autor2[i];
                                generor[tam] = genero2[i];
                                statusr[tam] = status2[i];
                                tam++;
                            }
                        }
                        break;
                    default:
                }

                BufferedWriter fw = new BufferedWriter(new FileWriter("pesquisa_resultado.txt"));          
                PrintWriter pw = new PrintWriter (fw);

                for(int i = 0;i<tam;i++){
                    pw.println(titulor[i]+";"+anodolivror[i]+";"+editorar[i]+";"+autorr[i]+";"+generor[i]+";"+statusr[i]);
                }
                fw.close();
                fr.close();
                if(tam==0){
                    JOptionPane.showMessageDialog(rootPane, "nenhum livro encontrado", "Aviso", JOptionPane.WARNING_MESSAGE);
                }else{
                    resultado frame1 = new resultado();
                    frame1.setVisible(rootPaneCheckingEnabled);
                    pesquisarLivro.this.dispose();
                }
            } catch (IOException e){

            }
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarAcaoActionPerformed

    private void pesquisaConteudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaConteudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaConteudoActionPerformed

    private void livrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livrosMouseClicked
        String titulo2, autor2, genero2,anodolivro2, editora2,status2;
        
        titulo2 = (String) livros.getValueAt(livros.getSelectedRow(), 0);
        anodolivro2 = (String) livros.getValueAt(livros.getSelectedRow(), 1);
        editora2 = (String) livros.getValueAt(livros.getSelectedRow(), 2);
        autor2 = (String) livros.getValueAt(livros.getSelectedRow(), 3);
        genero2 = (String) livros.getValueAt(livros.getSelectedRow(), 4);
        status2 = (String) livros.getValueAt(livros.getSelectedRow(), 5);
        
        BufferedWriter fw;          
        try {
            fw = new BufferedWriter(new FileWriter("pesquisa_resultadoE.txt"));
            PrintWriter pw = new PrintWriter (fw);
            pw.println(titulo2+";"+anodolivro2+";"+editora2+";"+autor2+";"+genero2+";"+status2+";1");
            fw.close();
            
            resultadoLivro frame1 = new resultadoLivro();
            frame1.setVisible(rootPaneCheckingEnabled);
            pesquisarLivro.this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(pesquisarLivro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_livrosMouseClicked

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        livros frame1 = new livros();
        frame1.setVisible(rootPaneCheckingEnabled);
        pesquisarLivro.this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesquisarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesquisarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesquisarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesquisarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pesquisarLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable livros;
    private javax.swing.JComboBox<String> pesquisa;
    private javax.swing.JTextField pesquisaConteudo;
    private javax.swing.JButton pesquisarAcao;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
