package codigos;


import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cliente
 */
public class relatorio extends javax.swing.JFrame {

    /**
     * Creates new form notificacao
     */

    public relatorio() {
        initComponents();
        Color fundo = new Color(253,236,166);
        getContentPane().setBackground(fundo);
         try {
            // TODO add your handling code here:
            Arquivo2();
        } catch (IOException ex) {
            
        }
        tabela_emprestimo.getColumnModel().getColumn(6).setWidth(0); tabela_emprestimo.getColumnModel().getColumn(6).setMinWidth(0); tabela_emprestimo.getColumnModel().getColumn(6).setMaxWidth(0); 
    }
    public void Arquivo2() throws IOException {
        BufferedReader fr = new BufferedReader(new FileReader("Emprestimos.txt"));
        String titulo2[] = new String[1000];
        String autor2[] = new String[1000];
        String genero2[] = new String[1000];
        String protocolo2[] = new String[1000];
        String dia2[] = new String[1000];  
        String mes2[] = new String[1000];  
        String ano2[] = new String[1000];  
        String leitor2[] = new String[1000];   
        String telefone[] = new String[1000];
        try {
            int q= 0;
            String linha;
            
            while(fr.ready()){
                linha = fr.readLine();
                String[] campos = linha.split(";");
                titulo2[q] = campos[0];
                autor2[q] = campos[3];
                genero2[q] = campos[4];
                leitor2[q] = campos[5];
                telefone[q] = campos[6];
                dia2[q] = campos[7];
                mes2[q] = campos[8];
                ano2[q] = campos[9];
                protocolo2[q] = campos[10];
                
                DefaultTableModel teste = (DefaultTableModel) tabela_emprestimo.getModel();
                Object[] dados = {protocolo2[q],titulo2[q],autor2[q],genero2[q],leitor2[q],dia2[q]+"/"+mes2[q]+"/"+ano2[q],telefone[q]};
                teste.addRow(dados);

                q++;
            }
            
            
            fr.close();
        
        }catch (IOException e){
            System.out.println("Erro na leitura do arquivo.");
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_emprestimo = new javax.swing.JTable();
        voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("blioteca Chá da Tarde");
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 50)); // NOI18N
        jLabel4.setText("Emprestimos");

        jLabel1.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jPanel1.setBackground(new java.awt.Color(253, 236, 166));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tabela_emprestimo.setBackground(new java.awt.Color(255, 255, 153));
        tabela_emprestimo.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        tabela_emprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Protocolo", "Titulo", "Autor", "Genero", "Leitor", "Data de devolução", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_emprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_emprestimoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_emprestimo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jScrollPane1)
                    .addGap(7, 7, 7)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        voltar.setBackground(new java.awt.Color(255, 255, 153));
        voltar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        jLabel2.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(voltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 219, Short.MAX_VALUE)
                        .addComponent(voltar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(768, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabela_emprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_emprestimoMouseClicked
        String protocolo2, titulo2, autor2, genero2, leitor2, data2, telefone2;
        
        protocolo2 = (String) tabela_emprestimo.getValueAt(tabela_emprestimo.getSelectedRow(), 0);
        titulo2 = (String) tabela_emprestimo.getValueAt(tabela_emprestimo.getSelectedRow(), 1);
        autor2 = (String) tabela_emprestimo.getValueAt(tabela_emprestimo.getSelectedRow(), 2);
        genero2 = (String) tabela_emprestimo.getValueAt(tabela_emprestimo.getSelectedRow(), 3);
        leitor2 = (String) tabela_emprestimo.getValueAt(tabela_emprestimo.getSelectedRow(), 4);
        data2 = (String) tabela_emprestimo.getValueAt(tabela_emprestimo.getSelectedRow(), 5);
        telefone2 = (String) tabela_emprestimo.getValueAt(tabela_emprestimo.getSelectedRow(), 6);
        
        BufferedWriter fw;          
        try {
            fw = new BufferedWriter(new FileWriter("relatorio_resultado.txt"));
            PrintWriter pw = new PrintWriter (fw);
            pw.println(protocolo2+";"+titulo2+";"+autor2+";"+genero2+";"+leitor2+";"+data2+";"+telefone2);
            fw.close();
            
            resultadoRelatorio frame1 = new resultadoRelatorio();
            frame1.setVisible(rootPaneCheckingEnabled);
            relatorio.this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(pesquisarLivro.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tabela_emprestimoMouseClicked

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        comeco frame1 = new comeco();
        frame1.setVisible(rootPaneCheckingEnabled);
        relatorio.this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_emprestimo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
